---
name: helm
description: A buildkite plugin to update helm tarballs
author: https://github.com/datumforge
requirements:
  - helm
  - yq
configuration:
  properties:
    user:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
    ssh_commit: 
      type: boolean
    message:
      type: string