#!/bin/bash

set -ux
  
find . -name Chart.yaml -type f | while read -r chartfile; do
    chart_dir=$(dirname "$chartfile")
    dep_length=$(yq '.dependencies | length' "$chartfile")
    if [[ "${dep_length}" -gt "0" ]]; then
        pushd "$chart_dir" || exit 1
        helm dependency update
        popd || exit 1
    else
        echo "Skipping $chartfile since no dependencies were found"
        continue
    fi
done

result=$(git diff --exit-code)

message=${BUILDKITE_PLUGIN_HELM_MESSAGE:-"Update Helm Tarballs"}

if [ "${result}" -ne 0 ]; then
    if [[ -n ${BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME+x} ]]
    then
    git config user.name "$BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME"
    fi

    if [[ -n ${BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL+x} ]]
    then
    git config user.email "$BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL"
    fi

    git checkout -b "${BUILDKITE_BRANCH}"
    git add .
    git commit -m "${message}"
    git push origin "${BUILDKITE_BRANCH}"
else
  echo "--- No changes to commit"
fi

exit 0