#!/bin/bash

set -ux
      
find . -name Chart.yaml -type f | while read -r chartfile; do
    chartdir=$(dirname "$chartfile")
    deplength=$(/tmp/yq '.dependencies | length' "$chartfile")
    if [ "$deplength" -gt "0" ]; then
        pushd "$chartdir" || exit 1
        /tmp/helm dependency update
        popd || exit 1
    else
        echo "Skipping $chartfile since no dependencies were found"
        continue
    fi
            
    git add "${chartdir}"
done

git diff --cached --exit-code > /dev/null
result=$?

message=${BUILDKITE_PLUGIN_HELM_MESSAGE:-"Update Helm Tarballs"}

if [ $result -ne 0 ]; then
    if [[ -n ${BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME+x} ]]
    then
    git config user.name "$BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME"
    fi

    if [[ -n ${BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL+x} ]]
    then
    git config user.email "$BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL"
    fi

    git add .
    git checkout -b "${BUILDKITE_BRANCH}"
    git commit -m "${message}"
    git push origin "${BUILDKITE_BRANCH}"
else
  echo "--- No changes to commit"
fi
