#!/bin/bash

set -o errexit # script exits when a command fails == set -e
set -o nounset # script exits when tries to use undeclared variables == set -u
set -o pipefail # causes pipelines to retain / set the last non-zero status

# Install yq, if not available
which yq || (apt-get install yq -y)

# Install helm, if not available
which helm || (apt-get install helm -y)

exit 0